image: nixos/nix:latest

variables:
  GIT_SUBMODULE_STRATEGY: none
  NIX_CONFIG: "extra-experimental-features = nix-command flakes"
  http_proxy: $CODE_PROXY
  https_proxy: $CODE_PROXY
  no_proxy: $CODE_NO_PROXY,$CI_REGISTRY,127.0.0.1,captain.rtf.siemens.net,.code.siemens.io,code.siemens.io

default:
  before_script:
    - git config --global url."${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}".insteadOf "${CI_SERVER_URL}"

pages:
  script:
    - nix build .#quartz-gitlab
    - cp -r result/public public
  artifacts:
    paths: [public]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
