# The Docker image that will be used to build your app
image: node:22.14.0
pages:
  script:
    - npm config set fund false
    - npm config set audit false
    - npm ci --no-audit --no-fund
    - npx quartz build
  artifacts:
    paths: [public]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
