name: Deploy to Codeberg Pages

on:
  push:
    branches:
      - v4

env:
  NIX_CONFIG: "extra-experimental-features = nix-command flakes"

jobs:
  deploy:
    runs-on: docker
    container:
      image: nixos/nix:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build Quartz
        run: nix build --impure --override-input eis-notes path:./content
        env:
          QUARTZ_BASE_URL: m4rc2a.codeberg.page/eis-wiki/
      - name: Deploy to Codeberg Pages
        uses: actions/pages-action@v1
        with:
          directory: result/public
